### ISSUE TITLE
Is there a way to fix OpROM problems?

### ISSUE THREAD

**Issue by leomeinel** [kmille/cryptboot#2]
Hello,

I was wondering if there is a way to use [OpROMs](https://wiki.archlinux.org/title/Unified_Extensible_Firmware_Interface/Secure_Boot#Using_your_own_keys) that are signed with other certificates than my own without enrolling those certificates into my db.
Really more of a question now than an issue, but it at least is somewhat related :)
Feel free to close this anytime.

**Comment by LeoMeinel** [comment]
If you are interested in my exact setup that the OpROM error occurs on here is a Link: https://github.com/LeoMeinel/mdadm-encrypted-btrfs/tree/2.0.10

It occurs just after enrolling the keys and rebooting.

**Comment by LeoMeinel** [comment]
Note: The keys are added successfully top /boot/efikeys/db.auth
The only thing failing is the enrolling.
